# Generated by Django 5.1.5 on 2026-01-20 21:48

from django.db import migrations, models


def dedupe_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    seen = set()
    for user in User.objects.exclude(email__isnull=True).exclude(email='').order_by('id'):
        email_key = user.email.lower()
        if email_key in seen:
            user.email = f"{user.email}+dup{user.id}"
            user.save(update_fields=['email'])
        else:
            seen.add(email_key)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_emails, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
