# Generated by Django 5.1.5 on 2026-01-20 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('image', 'Image'), ('other', 'Other')], max_length=20)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('excel_rows', models.IntegerField(blank=True, null=True)),
                ('excel_columns', models.IntegerField(blank=True, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
