# Generated by Django 5.1.5 on 2026-01-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='excel_columns_list',
            field=models.JSONField(blank=True, help_text='Stores column names', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='excel_data',
            field=models.JSONField(blank=True, help_text='Stores Excel data preview as JSON', null=True),
        ),
    ]
